name: Deploy to Prod

description: "Выкачка образа на прод-сервер через SSH"

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Версия Docker-образа для выкатки в прод"

jobs:
  deploy:
    name: 🚀 Deploy version to production server
    runs-on: ubuntu-latest
    env:
      REGISTRY: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: 📃 Лог версии и реестра
        run: |
          echo "Будем деплоить версию: $VERSION"
          echo "Из реестра: $REGISTRY"

      - name: ✨ Проверка доступности образа в YCR
        run: |
          echo "Проверяем наличие тега $VERSION\_latest в YCR..."
          docker manifest inspect $REGISTRY:${VERSION}_latest >/dev/null || {
            echo "❌ Образ с тегом ${VERSION}_latest не найден в Container Registry";
            exit 1;
          }
          echo "✅ Образ найден."

      - name: 🚚 Подключение к серверу и деплой
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "=== Начинаем деплой на сервер ==="

            echo "1. Получение YC access token..."
            echo '${{ secrets.YC_SERVICE_KEY }}' > key.json
            echo "key.json содержимое (безопасно скрыто)"
            ACCESS_TOKEN=$(cat key.json | jq -r .access_token)
            echo "2. Логинимся в Docker Registry..."
            echo "$ACCESS_TOKEN" | docker login --username oauth --password-stdin cr.yandex

            echo "3. Остановка и удаление предыдущего контейнера..."
            docker stop app || true
            docker rm app || true

            echo "4. Пулл образа..."
            docker pull $REGISTRY:${VERSION}_latest

            echo "5. Запуск контейнера..."
            docker run -d --name app -p 80:3000 $REGISTRY:${VERSION}_latest

            echo "6. Проверка контейнера..."
            docker ps | grep app
            echo "✅ Деплой завершён."

      - name: 📊 Добавление комментария в GitHub Issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.inputs.version }} 
          body: |
            🌐 Релиз **${{ github.event.inputs.version }}** выкачан в прод 
            📅 Дата: $(date +%F)
            👤 Автор: @${{ github.actor }}
            📦 Образ: `${{ env.REGISTRY }}:${{ env.VERSION }}_latest`
