name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Версия образа"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_SERVICE_KEY }}" > key.json
          docker login --username oauth --password-stdin cr.yandex <<< "$(cat key.json | jq -r .access_token)"

      - name: Pull and deploy image on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo '${{ secrets.YC_SERVICE_KEY }}' > key.json
            ACCESS_TOKEN=$(cat key.json | jq -r .access_token)
            docker login --username oauth --password "$ACCESS_TOKEN" cr.yandex
            docker stop app || true
            docker rm app || true
            docker pull $REGISTRY:${VERSION}_latest
            docker run -d --name app -p 80:3000 $REGISTRY:${VERSION}_latest
