name: CI/CD Deploy to Prod

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Версия образа"
                required: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t app .

            - name: Save Docker image to tar
              run: docker save app > app.tar

            - name: Cleanup old archive on server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.VM_IP }}
                  username: ${{ secrets.VM_SSH_USER }}
                  key: ${{ secrets.VM_SSH_KEY }}
                  script: rm -rf /tmp/app.tar

            - name: Copy Docker image archive to server
              uses: appleboy/scp-action@v0.1.5
              with:
                  host: ${{ secrets.VM_IP }}
                  username: ${{ secrets.VM_SSH_USER }}
                  key: ${{ secrets.VM_SSH_KEY }}
                  source: "app.tar"
                  target: "/tmp/app.tar"

            - name: Deploy and run Docker container on server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.VM_IP }}
                  username: ${{ secrets.VM_SSH_USER }}
                  key: ${{ secrets.VM_SSH_KEY }}
                  script: |
                      docker load < /tmp/app.tar
                      docker stop app || true
                      docker rm app || true
                      docker run -d --name app -p 80:3000 app:latest
                      rm -f /tmp/app.tar
