name: Release

on:
  workflow_dispatch:

permissions:
  contents: write  
  issues: write     

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.run_number }}
      REGISTRY: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Create release branch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b releases/${VERSION}
          git push --set-upstream origin releases/${VERSION}

      - name: Build Docker image
        run: docker build -t $REGISTRY:${VERSION} -t $REGISTRY:${VERSION}_latest .

      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_SERVICE_KEY }}" > key.json
          docker login --username oauth --password-stdin cr.yandex <<< "$(jq -r .access_token < key.json)"

      - name: Push Docker images
        run: |
          docker push $REGISTRY:${VERSION}
          docker push $REGISTRY:${VERSION}_latest

      - name: Create git tag
        run: |
          git tag ${VERSION}
          git push origin ${VERSION}

      - name: Generate commit list
        id: changelog
        run: |
          git fetch --tags
          PREV=$(git tag --sort=-creatordate | grep -E '^[0-9]+$' | head -n2 | tail -n1)
          if [ -z "$PREV" ]; then
            git log --oneline > commits.txt
          else
            git log $PREV..HEAD --oneline > commits.txt
          fi
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          cat commits.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Create release issue
        run: |
          gh issue create \
            --title "Release $VERSION" \
            --body "**Дата:** $(date)\n**Автор:** ${{ github.actor }}\n**Версия:** $VERSION\n\n**Коммиты:**\n${{ env.COMMITS }}\n\nDocker: $REGISTRY:$VERSION"
